import "@/styles/globals.css";

import type { Metadata } from "next";

import { HomeSideBar, MeetingRoomSideBar } from "@/components";
import { cn } from "@/lib/utils";
import { AppProviders } from "@/provider";
import { SpoqaHanSansNeo } from "@/styles/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={SpoqaHanSansNeo.variable}>
      <body className={cn("font-spoqa-han-sans-neo", "w-full", "h-dvh")}>
        <AppProviders>
          {true ? <HomeSideBar /> : <MeetingRoomSideBar />}
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
