import "@/styles/globals.css";

import type { Metadata } from "next";

import { cn } from "@/lib/utils";
import { SpoqaHanSansNeo } from "@/styles/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={SpoqaHanSansNeo.variable}>
      <body className={cn("font-spoqa-han-sans-neo", "w-full", "h-dvh")}>
        {children}
      </body>
    </html>
  );
}
